version: '3'

services:
  app:
    image: srigi/webauthn-nette/app
    build:
      context: .
      args:
        IS_PROD_BUILD: 0
    env_file:
      - .env
    environment:
      APP_DEBUG: 1
      APP_ENV: local
      DATABASE_URL: sqlsrv:Server=database;Database=webauthn
      DATABASE_USER: sa
      DATABASE_PASSWORD: S3cret_123
    depends_on:
      - database
    volumes:
      - ./.data:/app/.data
      - ./.docker/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./config:/app/config
      - ./logs:/app/logs
      - ./src:/app/src
      - ./temp:/app/temp
      - ./www:/app/www

  webserver:
    image: srigi/webauthn-nette/webserver
    build:
      context: .
      dockerfile: Dockerfile.webserver
      args:
        CONFIG: 'nginx.dev-ssl.conf'
        STATIC_FILES_IMAGE: srigi/webauthn-nette/app
    env_file:
      - .env
    environment:
      BACKEND_SERVICE: app:9000
      FCGI_READ_TIMEOUT: 3600s
      HEALTHCHECK_TOKEN: secret
    ports:
      - 127.0.0.1:${HOST_APP_PORT}:8000

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: S3cret_123
      MSSQL_PID: Express # MSSQL Express edition (free)
    ports:
      - 127.0.0.1:${HOST_DATABASE_PORT}:1433
    volumes:
      - database:/var/opt/mssql
    restart: on-failure

volumes:
  database:
